apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 136314223160.dkr.ecr.us-east-1.amazonaws.com/docker-images-registry:backend
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
      imagePullSecrets: 
        - name: regcred

